/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatAutomationsRouteImport } from './routes/_chat.automations'
import { Route as ChatPluginsRouteImport } from './routes/_chat.plugins'
import { Route as ChatPullRequestsRouteImport } from './routes/_chat.pull-requests'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatWorkspaceRouteImport } from './routes/_chat.workspace'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ChatAutomationsIndexRouteImport } from './routes/_chat.automations.index'
import { Route as ChatAutomationsAutomationIdRouteImport } from './routes/_chat.automations.$automationId'
import { Route as ChatKanbanIndexRouteImport } from './routes/_chat.kanban.index'
import { Route as ChatKanbanProjectIdRouteImport } from './routes/_chat.kanban.$projectId'
import { Route as ChatPullRequestsIndexRouteImport } from './routes/_chat.pull-requests.index'
import { Route as ChatStudioIndexRouteImport } from './routes/_chat.studio.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAutomationsRoute = ChatAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPluginsRoute = ChatPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPullRequestsRoute = ChatPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatWorkspaceRoute = ChatWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => ChatRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatAutomationsIndexRoute = ChatAutomationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatAutomationsRoute,
} as any)
const ChatAutomationsAutomationIdRoute =
  ChatAutomationsAutomationIdRouteImport.update({
    id: '/$automationId',
    path: '/$automationId',
    getParentRoute: () => ChatAutomationsRoute,
  } as any)
const ChatKanbanIndexRoute = ChatKanbanIndexRouteImport.update({
  id: '/kanban/',
  path: '/kanban/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatKanbanProjectIdRoute = ChatKanbanProjectIdRouteImport.update({
  id: '/kanban/$projectId',
  path: '/kanban/$projectId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPullRequestsIndexRoute = ChatPullRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatPullRequestsRoute,
} as any)
const ChatStudioIndexRoute = ChatStudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/automations': typeof ChatAutomationsRouteWithChildren
  '/plugins': typeof ChatPluginsRoute
  '/pull-requests': typeof ChatPullRequestsRouteWithChildren
  '/settings': typeof ChatSettingsRoute
  '/workspace': typeof ChatWorkspaceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/kanban/$projectId': typeof ChatKanbanProjectIdRoute
  '/automations/': typeof ChatAutomationsIndexRoute
  '/kanban/': typeof ChatKanbanIndexRoute
  '/pull-requests/': typeof ChatPullRequestsIndexRoute
  '/studio/': typeof ChatStudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/plugins': typeof ChatPluginsRoute
  '/settings': typeof ChatSettingsRoute
  '/workspace': typeof ChatWorkspaceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/kanban/$projectId': typeof ChatKanbanProjectIdRoute
  '/automations': typeof ChatAutomationsIndexRoute
  '/kanban': typeof ChatKanbanIndexRoute
  '/pull-requests': typeof ChatPullRequestsIndexRoute
  '/studio': typeof ChatStudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_chat': typeof ChatRouteWithChildren
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/automations': typeof ChatAutomationsRouteWithChildren
  '/_chat/plugins': typeof ChatPluginsRoute
  '/_chat/pull-requests': typeof ChatPullRequestsRouteWithChildren
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/workspace': typeof ChatWorkspaceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_chat/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/_chat/kanban/$projectId': typeof ChatKanbanProjectIdRoute
  '/_chat/automations/': typeof ChatAutomationsIndexRoute
  '/_chat/kanban/': typeof ChatKanbanIndexRoute
  '/_chat/pull-requests/': typeof ChatPullRequestsIndexRoute
  '/_chat/studio/': typeof ChatStudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/logout'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/$threadId'
    | '/automations'
    | '/plugins'
    | '/pull-requests'
    | '/settings'
    | '/workspace'
    | '/auth/callback'
    | '/automations/$automationId'
    | '/kanban/$projectId'
    | '/automations/'
    | '/kanban/'
    | '/pull-requests/'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/logout'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/$threadId'
    | '/plugins'
    | '/settings'
    | '/workspace'
    | '/auth/callback'
    | '/automations/$automationId'
    | '/kanban/$projectId'
    | '/automations'
    | '/kanban'
    | '/pull-requests'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/_chat'
    | '/app'
    | '/forgot-password'
    | '/logout'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_chat/$threadId'
    | '/_chat/automations'
    | '/_chat/plugins'
    | '/_chat/pull-requests'
    | '/_chat/settings'
    | '/_chat/workspace'
    | '/auth/callback'
    | '/_chat/automations/$automationId'
    | '/_chat/kanban/$projectId'
    | '/_chat/automations/'
    | '/_chat/kanban/'
    | '/_chat/pull-requests/'
    | '/_chat/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  AppRoute: typeof AppRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LogoutRoute: typeof LogoutRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/automations': {
      id: '/_chat/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof ChatAutomationsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plugins': {
      id: '/_chat/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof ChatPluginsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pull-requests': {
      id: '/_chat/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof ChatPullRequestsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/workspace': {
      id: '/_chat/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof ChatWorkspaceRouteImport
      parentRoute: typeof ChatRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/automations/': {
      id: '/_chat/automations/'
      path: '/'
      fullPath: '/automations/'
      preLoaderRoute: typeof ChatAutomationsIndexRouteImport
      parentRoute: typeof ChatAutomationsRoute
    }
    '/_chat/automations/$automationId': {
      id: '/_chat/automations/$automationId'
      path: '/$automationId'
      fullPath: '/automations/$automationId'
      preLoaderRoute: typeof ChatAutomationsAutomationIdRouteImport
      parentRoute: typeof ChatAutomationsRoute
    }
    '/_chat/kanban/': {
      id: '/_chat/kanban/'
      path: '/kanban'
      fullPath: '/kanban/'
      preLoaderRoute: typeof ChatKanbanIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/kanban/$projectId': {
      id: '/_chat/kanban/$projectId'
      path: '/kanban/$projectId'
      fullPath: '/kanban/$projectId'
      preLoaderRoute: typeof ChatKanbanProjectIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pull-requests/': {
      id: '/_chat/pull-requests/'
      path: '/'
      fullPath: '/pull-requests/'
      preLoaderRoute: typeof ChatPullRequestsIndexRouteImport
      parentRoute: typeof ChatPullRequestsRoute
    }
    '/_chat/studio/': {
      id: '/_chat/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof ChatStudioIndexRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatAutomationsRouteChildren {
  ChatAutomationsAutomationIdRoute: typeof ChatAutomationsAutomationIdRoute
  ChatAutomationsIndexRoute: typeof ChatAutomationsIndexRoute
}

const ChatAutomationsRouteChildren: ChatAutomationsRouteChildren = {
  ChatAutomationsAutomationIdRoute: ChatAutomationsAutomationIdRoute,
  ChatAutomationsIndexRoute: ChatAutomationsIndexRoute,
}

const ChatAutomationsRouteWithChildren = ChatAutomationsRoute._addFileChildren(
  ChatAutomationsRouteChildren,
)

interface ChatPullRequestsRouteChildren {
  ChatPullRequestsIndexRoute: typeof ChatPullRequestsIndexRoute
}

const ChatPullRequestsRouteChildren: ChatPullRequestsRouteChildren = {
  ChatPullRequestsIndexRoute: ChatPullRequestsIndexRoute,
}

const ChatPullRequestsRouteWithChildren =
  ChatPullRequestsRoute._addFileChildren(ChatPullRequestsRouteChildren)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatAutomationsRoute: typeof ChatAutomationsRouteWithChildren
  ChatPluginsRoute: typeof ChatPluginsRoute
  ChatPullRequestsRoute: typeof ChatPullRequestsRouteWithChildren
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatWorkspaceRoute: typeof ChatWorkspaceRoute
  ChatKanbanProjectIdRoute: typeof ChatKanbanProjectIdRoute
  ChatKanbanIndexRoute: typeof ChatKanbanIndexRoute
  ChatStudioIndexRoute: typeof ChatStudioIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatAutomationsRoute: ChatAutomationsRouteWithChildren,
  ChatPluginsRoute: ChatPluginsRoute,
  ChatPullRequestsRoute: ChatPullRequestsRouteWithChildren,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatWorkspaceRoute: ChatWorkspaceRoute,
  ChatKanbanProjectIdRoute: ChatKanbanProjectIdRoute,
  ChatKanbanIndexRoute: ChatKanbanIndexRoute,
  ChatStudioIndexRoute: ChatStudioIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  AppRoute: AppRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LogoutRoute: LogoutRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
